export const TOGGLE_STOPS_FILTER = 'SET_STOPS_FILTER'

export const FILTER_ALL = 'FILTER_ALL'
export const FILTER_WITHOUT_STOPS = 'FILTER_WITHOUT_STOPS'
export const FILTER_1_STOP = 'FILTER_1_STOP'
export const FILTER_2_STOPS = 'FILTER_2_STOPS'
export const FILTER_3_STOPS = 'FILTER_3_STOPS'
